### ISSUE TITLE
Import issue in `face_detection.py`

### ISSUE THREAD

**Issue by pyaf** [DevendraPratapYadav/gsoc18_RedHenLab#1]
Hi, I'm going through your repo. In `face_detection.py` you have imported `util` module [here](https://github.com/DevendraPratapYadav/gsoc18_RedHenLab/blob/master/video_processing_pipeline/face_detection.py#L34) but there's no `util.py` in the directory. I can see it is present in `2_face_detection/libs/tiny_faces`. This issue can be resolved by appending `2_face_detection/libs/tiny_faces` to sys.path.

**Comment by DevendraPratapYadav** [comment]
That path is already being appended to sys.path.
The `util.py` script is part of `tiny_faces` face detection algorithm. The files required by `tiny_faces` are currently placed in `2_face_detection/libs/tiny_faces` and this path is given as a dependency for `Stage 2-Face Detection` in `stages.py` [here](https://github.com/DevendraPratapYadav/gsoc18_RedHenLab/blob/master/video_processing_pipeline/stages.py#L93). All dependencies for various stages are specified in `stages.py`.

This path is then accessed and appended to sys.path in `face_detection.py` [line 30](https://github.com/DevendraPratapYadav/gsoc18_RedHenLab/blob/master/video_processing_pipeline/face_detection.py#L30). Please let me know if you face any errors while running the script.

**Comment by pyaf** [comment]
Oh okay, I tried import util before the line 30 in `face_detection.py`.

**Comment by pyaf** [comment]
I'm getting this error:
```
Traceback (most recent call last):                                                                                                                                                                                 
  File "face_detection.py", line 20, in <module>                                                                                                                                                                   
    import pylab as pl                                                                                                                                                                                             
  File "/root/miniconda3/envs/redhenED/lib/python3.5/site-packages/pylab.py", line 1, in <module>
    from matplotlib.pylab import *
  File "/root/miniconda3/envs/redhenED/lib/python3.5/site-packages/matplotlib/pylab.py", line 252, in <module>
    from matplotlib import cbook, mlab, pyplot as plt
  File "/root/miniconda3/envs/redhenED/lib/python3.5/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/root/miniconda3/envs/redhenED/lib/python3.5/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/root/miniconda3/envs/redhenED/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import (
  File "/root/miniconda3/envs/redhenED/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 19, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/root/miniconda3/envs/redhenED/lib/python3.5/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/root/miniconda3/envs/redhenED/lib/python3.5/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 54, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/root/miniconda3/envs/redhenED/lib/python3.5/site-packages/matplotlib/backends/qt_compat.py", line 158, in <module>
    raise ImportError("Failed to import any qt binding")
ImportError: Failed to import any qt binding
```
I've tried googling it, got no help. Do you have any ideas what's wrong with my system? It looks something related to plotting.

**Comment by DevendraPratapYadav** [comment]
Seems to be an error with `matplotlib`. I see you are using miniconda which may be missing some packages related to qt binding. 
Try the solutions given here:
https://github.com/matplotlib/matplotlib/issues/11929
https://stackoverflow.com/questions/52346254/importerror-failed-to-import-any-qt-binding-python-tensorflow

If that doesn't work, I would recommend installing Anaconda which has all necessary packages pre-installed.

**Comment by pyaf** [comment]
Alright, so it was nvidia driver issue. Working now.

**Comment by pyaf** [comment]
In the face_clustering step, I'm getting following error: 
```
(videopipelineenv) root@C.71008:~/gsoc18_RedHenLab/video_processing_pipeline$ python face_clustering.py 
SCRIPT_WORKING_DIRECTORY: /root/gsoc18_RedHenLab/video_processing_pipeline
Checking paths for all stages.
Begin Stage  7  :  Face Clustering
/root/gsoc18_RedHenLab/video_processing_pipeline/5_face_alignment/output/input.mp4_1_1.mp4_aligned.mp4
/root/gsoc18_RedHenLab/video_processing_pipeline/5_face_alignment/output/input.mp4_1_2.mp4_aligned.mp4
/root/gsoc18_RedHenLab/video_processing_pipeline/5_face_alignment/output/input.mp4_1_3.mp4_aligned.mp4
/root/gsoc18_RedHenLab/video_processing_pipeline/5_face_alignment/output/input.mp4_2_4.mp4_aligned.mp4
/root/gsoc18_RedHenLab/video_processing_pipeline/5_face_alignment/output/input.mp4_2_5.mp4_aligned.mp4
/root/gsoc18_RedHenLab/video_processing_pipeline/5_face_alignment/output/input.mp4_3_6.mp4_aligned.mp4
/root/gsoc18_RedHenLab/video_processing_pipeline/5_face_alignment/output/input.mp4_3_7.mp4_aligned.mp4
/root/gsoc18_RedHenLab/video_processing_pipeline/5_face_alignment/output/input.mp4_3_8.mp4_aligned.mp4
/root/gsoc18_RedHenLab/video_processing_pipeline/5_face_alignment/output/input.mp4_4_9.mp4_aligned.mp4
/root/gsoc18_RedHenLab/video_processing_pipeline/5_face_alignment/output/input.mp4_4_10.mp4_aligned.mp4
/root/gsoc18_RedHenLab/video_processing_pipeline/5_face_alignment/output/input.mp4_4_11.mp4_aligned.mp4
Unable to stop the stream: Inappropriate ioctl for device
/root/gsoc18_RedHenLab/video_processing_pipeline/5_face_alignment/output/input.mp4_4_12.mp4_aligned.mp4
Unable to stop the stream: Inappropriate ioctl for device
/root/gsoc18_RedHenLab/video_processing_pipeline/5_face_alignment/output/input.mp4_4_13.mp4_aligned.mp4
/root/gsoc18_RedHenLab/video_processing_pipeline/5_face_alignment/output/input.mp4_8_25.mp4_aligned.mp4
/root/gsoc18_RedHenLab/video_processing_pipeline/5_face_alignment/output/input.mp4_5_14.mp4_aligned.mp4
/root/gsoc18_RedHenLab/video_processing_pipeline/5_face_alignment/output/input.mp4_8_24.mp4_aligned.mp4
/root/gsoc18_RedHenLab/video_processing_pipeline/5_face_alignment/output/input.mp4_5_15.mp4_aligned.mp4
/root/gsoc18_RedHenLab/video_processing_pipeline/5_face_alignment/output/input.mp4_8_26.mp4_aligned.mp4
/root/gsoc18_RedHenLab/video_processing_pipeline/5_face_alignment/output/input.mp4_6_16.mp4_aligned.mp4
/root/gsoc18_RedHenLab/video_processing_pipeline/5_face_alignment/output/input.mp4_9_27.mp4_aligned.mp4
/root/gsoc18_RedHenLab/video_processing_pipeline/5_face_alignment/output/input.mp4_6_17.mp4_aligned.mp4
/root/gsoc18_RedHenLab/video_processing_pipeline/5_face_alignment/output/input.mp4_9_28.mp4_aligned.mp4
/root/gsoc18_RedHenLab/video_processing_pipeline/5_face_alignment/output/input.mp4_6_18.mp4_aligned.mp4
Unable to stop the stream: Inappropriate ioctl for device
/root/gsoc18_RedHenLab/video_processing_pipeline/5_face_alignment/output/input.mp4_6_19.mp4_aligned.mp4
Unable to stop the stream: Inappropriate ioctl for device
/root/gsoc18_RedHenLab/video_processing_pipeline/5_face_alignment/output/input.mp4_6_20.mp4_aligned.mp4
Unable to stop the stream: Inappropriate ioctl for device
/root/gsoc18_RedHenLab/video_processing_pipeline/5_face_alignment/output/input.mp4_9_30.mp4_aligned.mp4
/root/gsoc18_RedHenLab/video_processing_pipeline/5_face_alignment/output/input.mp4_7_21.mp4_aligned.mp4
/root/gsoc18_RedHenLab/video_processing_pipeline/5_face_alignment/output/input.mp4_9_29.mp4_aligned.mp4
/root/gsoc18_RedHenLab/video_processing_pipeline/5_face_alignment/output/input.mp4_7_22.mp4_aligned.mp4
/root/gsoc18_RedHenLab/video_processing_pipeline/5_face_alignment/output/input.mp4_7_23.mp4_aligned.mp4
Traceback (most recent call last):
  File "face_clustering.py", line 287, in <module>
    result = clustering(face_tracks, features=embeddingData)
  File "/root/miniconda3/envs/videopipelineenv/lib/python3.5/site-packages/pyannote/algorithms/clustering/hac/hac.py", line 204, in __call__
    for i, current_state in enumerate(self._iterate()):
  File "/root/miniconda3/envs/videopipelineenv/lib/python3.5/site-packages/pyannote/algorithms/clustering/hac/hac.py", line 172, in _iterate
    self.model.update(clusters, into, parent=self)
  File "/root/miniconda3/envs/videopipelineenv/lib/python3.5/site-packages/pyannote/algorithms/clustering/hac/model.py", line 164, in update
    self._similarity.pop((i, j), default=None)
  File "/root/miniconda3/envs/videopipelineenv/lib/python3.5/site-packages/sortedcontainers/sorteddict.py", line 427, in pop
    self._list_remove(key)
  File "/root/miniconda3/envs/videopipelineenv/lib/python3.5/site-packages/sortedcontainers/sortedlist.py", line 2025, in remove
    raise ValueError('{0!r} not in list'.format(value))
ValueError: (7, 19) not in list
```

there are two things to notice: `Unable to stop the stream: Inappropriate ioctl for device` while it is trying to extract the frames from the face aligned clips. Googling a bit about this suggests installing `ffmpeg` and recompiling opencv. and probably the last error (ValueError: (7, 19)....) is because of these unable to stop the stream errors. Any ideas?

**Comment by pyaf** [comment]
One quick question: Why are you initializing `MTCNN_detector` at every iteration [here](https://github.com/DevendraPratapYadav/gsoc18_RedHenLab/blob/master/video_processing_pipeline/face_detection.py#L526), why not define it globally?

**Comment by DevendraPratapYadav** [comment]
1. `Unable to stop the stream: Inappropriate ioctl for device`
If I recall correctly, you get this for videos with zero frames i.e. no face was detected in those videos and opencv can't properly read the video file. This is fine.

2. `ValueError: (7, 19) not in list`
I previously encountered error this due to `pyannote-video` requiring specific versions of `sortedcollections` and `sortedcontainers`. Try removing `pyannote-video`, `sortedcollections` and `sortedcontainers`, then run lines 19 to 21 from [setup.sh](https://github.com/DevendraPratapYadav/gsoc18_RedHenLab/blob/master/video_processing_pipeline/setup.sh#L19)

**Comment by DevendraPratapYadav** [comment]
> One quick question: Why are you initializing `MTCNN_detector` at every iteration [here](https://github.com/DevendraPratapYadav/gsoc18_RedHenLab/blob/master/video_processing_pipeline/face_detection.py#L526), why not define it globally?

You could do that. I recall that I encountered some error with tensorflow's execution when defining it globally.

**Comment by pyaf** [comment]
>If I recall correctly, you get this for videos with zero frames i.e. no face was detected in those videos and opencv can't properly read the video file. This is fine.

Yes, correct. I've two more questions. 

1. The `MTCNN_detector.detect_faces` returns confidence score for each detected face together with the bounding box [here](https://github.com/DevendraPratapYadav/gsoc18_RedHenLab/blob/master/video_processing_pipeline/face_detection.py#L88).  Why aren't you using a threshold score to filter out the detections? I see all true positives have a confidence score above 0.95, I think we can remove many false positives (there are a few, with confidence scores between 0.7 to 0.9) using a threshold score of 0.9 or above.

2. Your comment [here](https://github.com/DevendraPratapYadav/gsoc18_RedHenLab/blob/master/video_processing_pipeline/face_detection.py#L134) What's the point of detecting on the third frame of each shot, when we have already specified the sampling rate? and why only the third frame of each shot?

**Comment by DevendraPratapYadav** [comment]
> Yes, correct. I've two more questions.
> 
> 1. The `MTCNN_detector.detect_faces` returns confidence score for each detected face together with the bounding box [here](https://github.com/DevendraPratapYadav/gsoc18_RedHenLab/blob/master/video_processing_pipeline/face_detection.py#L88).  Why aren't you using a threshold score to filter out the detections? I see all true positives have a confidence score above 0.95, I think we can remove many false positives (there are a few, with confidence scores between 0.7 to 0.9) using a threshold score of 0.9 or above.

You can use additional thresholds but it may depend on use case, eg. dark videos may need lower threshold. We used Tiny Faces algorithm for face detection which performed much better.
> 2. Your comment [here](https://github.com/DevendraPratapYadav/gsoc18_RedHenLab/blob/master/video_processing_pipeline/face_detection.py#L134) What's the point of detecting on the third frame of each shot, when we have already specified the sampling rate? and why only the third frame of each shot?

The comment mentions `to ensure new faces in shot are tracked quickly`. We essentially reset the sampling process to start from the first few frames of a new shot (otherwise we will miss faces in some early frames of new shot as previous face track will have stopped). Nothing special about 3rd frame, I just skipped a few frames in case of errors in shot boundaries or shot transitions.

**Comment by pyaf** [comment]
I've one more question. This project is only a video processing pipeline, while your GSoC project was on multi-modal emotion detection (correct me if I'm wrong). Red Hen Lab has again listed this project for this year's GSoC. So, this year's work has to be done on top of your code, or it can be independent?
