### ISSUE TITLE
How to get eye gaze from face landmark?

### ISSUE THREAD

**Issue by 1158755456** [DevendraPratapYadav/gsoc18_RedHenLab#4]

**Comment by 1158755456** [comment]
How to get eye gaze from face landmark?

**Comment by DevendraPratapYadav** [comment]
The output of '6. Feature Extraction' stage should contain eye gaze angles in the same format as 'Gaze related' features in [OpenFace ](https://github.com/TadasBaltrusaitis/OpenFace/wiki/Output-Format)(which is used to extract the features).
If you just want the eye gaze features, you can also directly process your video using [OpenFace](https://github.com/TadasBaltrusaitis/OpenFace/wiki).

**Comment by 1158755456** [comment]
> The output of '6. Feature Extraction' stage should contain eye gaze angles in the same format as 'Gaze related' features in [OpenFace ](https://github.com/TadasBaltrusaitis/OpenFace/wiki/Output-Format)(which is used to extract the features).
> If you just want the eye gaze features, you can also directly process your video using [OpenFace](https://github.com/TadasBaltrusaitis/OpenFace/wiki).

ok thank you . I really want to know the algorithm，I thought you did it yourself. Anyway, thank you.
